### ISSUE TITLE
Animator not stop when exit activity.

### ISSUE THREAD

**Issue by Tinker-S** [daimajia/AndroidViewAnimations#103]
I set repeat count to INFINIT, and then exit MyActivity in demo project. I found  that the animator not stop. And this will cause the activity leak. May be we can **addOnAttachStateChangeListener** for the target view. When target view is detached, we should not start animator set again in **onAnimationEnd**.

**Comment by qdxxxx** [comment]
You can do that : YoYo.YoYoString viewAnimator=YoYo.with......playOn(); ,when activity destory call the viewAnimator.stop , hope that can help you.

**Comment by daimajia** [comment]
@qdxxxx Good answer.
