### ISSUE TITLE
Animation is not playing on Phone

### ISSUE THREAD

**Issue by fabio001** [daimajia/AndroidViewAnimations#105]
Hi,
I think my problem is related to API level. When I try the animations on emulator at API level 25, animations work; however, when I try it with my phone (API 19), animations do not work. Is there anything am I missing? As I read it is supporting API>=14, am I right?
Thanks.
Fabio

**Comment by daimajia** [comment]
Have you ever disabled your phone animation for saving the battery?

**Comment by fabio001** [comment]
Thank you so much. The problem was that I closed the animation on my phone.
