### ISSUE TITLE
Animate hidden view

### ISSUE THREAD

**Issue by azurh** [daimajia/AndroidViewAnimations#107]
Hi,

I have a view which visibility is set to `View.GONE`. How can I show it with `Techniques.FadeIn` animation?

I tried also setting it to `View.INVISIBLE` just before playing the animation, without luck.

Here is the code I'm using:

```java
mEmptyView.setVisibility(View.INVISIBLE);
YoYo.with(Techniques.FadeIn).
    duration(200).
    playOn(mEmptyView);
```

The `emptyView` won't show.

**Comment by po10cio** [comment]
You can try 
`Yoyo.with(Technique.FadeIn)
.duration(200)
.onEnd(animator->{emptyView.setVisibility(View.Visible)})
.playOn(emptyView)`
