### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by aboulfotoh** [daimajia/AndroidViewAnimations#111]
Error:Module 'com.daimajia.androidanimations:library:2.2' depends on one or more Android Libraries but is a jar

**Comment by SeachForLife** [comment]
two way to solve the problem:
1. You must add compile 'com.daimajia.androidanimations:library:2.2@aar' in your dependencies,not 'com.daimajia.androidanimations:library:2.2'
2. Github project releases can find in  "https://jitpack.io". You also can get the git project into your build by this way.

**Comment by aboulfotoh** [comment]
Thanks it worked fine now 👍 💯 🥇
