### ISSUE TITLE
proguard not works!

### ISSUE THREAD

**Issue by HosseinKurd** [daimajia/AndroidViewAnimations#118]
Animation code is

`        YoYo.with(Techniques.Landing)`
`                .duration(3000)`
`                .onEnd(new YoYo.AnimatorCallback() {`
`                    @Override`
`                    public void call(Animator animator) {`
`                        checkSolution();`
`                    }`
`                })`
`                .playOn(findViewById(R.id.img_logo_splash));`

i use the below commands on app proguard

`-dontwarn com.daimajia.`
`-keep class com.daimajia.easing. { *; }`
`-keep interface com.daimajia.easing. { *; }`
`-keep public class com.daimajia.androidanimations. { *; }`
`-keep public class com.daimajia.androidanimations.library.specials.in.LandingAnimator. { *; }`
`-keep class com.daimajia.androidanimations.** { *; }`
`-keep interface com.daimajia.androidanimations.** { *; }`
`-keep class com.daimajia.* { *; }`
`-keep interface com.daimajia.* { *; }`
`-keep public class com.daimajia.* { *; }`

But App Crashed !

**Comment by daimajia** [comment]
Check out this thread https://github.com/daimajia/AndroidViewAnimations/issues/68 , it may help you.
