### ISSUE TITLE
Can not use on threads.

### ISSUE THREAD

**Issue by kusal772** [daimajia/AndroidViewAnimations#162]
Here is my code:

```java
package com.dsf.ChatNagin;

import android.os.Bundle;
import android.view.WindowManager;
import android.widget.ProgressBar;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.daimajia.androidanimations.library.Techniques;
import com.daimajia.androidanimations.library.YoYo;

import java.util.Objects;

import static java.lang.Thread.sleep;

@SuppressWarnings("ALL")
public class Load extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_load);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        Objects.requireNonNull(getSupportActionBar()).hide();

        YoYo.with(Techniques.FadeIn).duration(2000).repeat(0).playOn(findViewById(R.id.activity_load));

        ProgressBar progressBar = findViewById(R.id.loadingProgressBar);

        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                try {
                    sleep(15);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            for (int i = 100; i >= 0; i--) {
                try {
                    sleep(10);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            YoYo.with(Techniques.FadeOut).duration(1000).playOn(findViewById(R.id.loadingPageIcon));
        }).start();
    }
}
```

When I am running the code I can see my fade-in animation but when fade-out animation is launching the app is keeps stopping. So what can I do?

Here is a video... The activity must fade in then fade out but it isn't...

https://user-images.githubusercontent.com/76206136/116975161-d28a6580-acdc-11eb-8dd0-4eb549e30e18.mp4

It is a big error. Resolve it.

**Comment by Androior** [comment]
Hi @kusal772 , sorry for a bit late response, I'm currently working on one project where I need so much animations of this type and then saw your comment. Let's get straight to the point.  First thing first, you can't invoke animate function on background thread directly. So, personally I would take a look at this solution 
https://stackoverflow.com/questions/44308697/start-an-animation-from-a-task-running-on-a-background-thread
or here is shorter one according to your code snippet: 
`public class MainActivity extends AppCompatActivity {
TextView textView;
YoYo yoYo;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        Objects.requireNonNull(getSupportActionBar()).hide();

        YoYo.with(Techniques.FadeIn).duration(2000).repeat(0).playOn(findViewById(R.id.txt));

        ProgressBar progressBar = findViewById(R.id.loadingProgressBar);

        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                try {
                    Thread.sleep(15);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            for (int i = 100; i >= 0; i--) {
                try {
                    Thread.sleep(15);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    YoYo.with(Techniques.BounceInLeft).duration(3000).playOn(findViewById(R.id.txt));
                }
            });
        }).start();
    }

}`

**Comment by ghost** [comment]
Hi @kusal772, here is solution for this issue. And I wouldn't say it's library issue because it's not possible in android to invoke animate method on object from Animator class but you can have a look at this solution from stackoverflow: 

https://stackoverflow.com/questions/44308697/start-an-animation-from-a-task-running-on-a-background-thread

My solution would be much shorter and simpler one, so based on your logic  I would suggest adding this line of code 

```java
package com.dsf.ChatNagin;

import android.os.Bundle;
import android.view.WindowManager;
import android.widget.ProgressBar;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.daimajia.androidanimations.library.Techniques;
import com.daimajia.androidanimations.library.YoYo;

import java.util.Objects;

import static java.lang.Thread.sleep;

@SuppressWarnings("ALL")
public class Load extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_load);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        Objects.requireNonNull(getSupportActionBar()).hide();

        YoYo.with(Techniques.FadeIn).duration(2000).repeat(0).playOn(findViewById(R.id.activity_load));

        ProgressBar progressBar = findViewById(R.id.loadingProgressBar);

        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                try {
                    sleep(15);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            for (int i = 100; i >= 0; i--) {
                try {
                    sleep(10);
                    progressBar.setProgress(i);
                } catch (InterruptedException ignored) {
                }
            }
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    YoYo.with(Techniques.FadeOut).duration(1000).playOn(findViewById(R.id.loadingPageIcon));
                }
            });
            //  YoYo.with(Techniques.FadeOut).duration(1000).playOn(findViewById(R.id.loadingPageIcon)); - this line is moved upper 
            // inside runOnUiThread method
        }).start();
    }
}
```
I hope you would find this suggestion useful
Cheers!

**Comment by daimajia** [comment]
Android UI update MUST be involk from main thread. [https://stackoverflow.com/a/16483544](url)
