### ISSUE TITLE
Repeat animations

### ISSUE THREAD

**Issue by shinayser** [daimajia/AndroidViewAnimations#22]
A method should be included on "YoYo" class to allow repeat! That would be very handy =)

Thankyou for great lib!

**Comment by robertoestivill** [comment]
You can have this effect by calling `setRepeatCount` on the `ObjectAnimator`'s inside the `BaseViewAnimator` implementation. 

This is a modified `ZoomOutAnimator` based on the library class.

```Java

public class ZoomOutAnimator extends BaseViewAnimator {
    @Override
    protected void prepare(View target) {
        ObjectAnimator oa1 = ObjectAnimator.ofFloat(target, "alpha", 1, 0, 0);
        ObjectAnimator oa2 = ObjectAnimator.ofFloat(target, "alpha", 1, 0, 0);
        ObjectAnimator oa3 = ObjectAnimator.ofFloat(target, "scaleX", 1, 0.3f, 0);
        ObjectAnimator oa4 = ObjectAnimator.ofFloat(target, "scaleY", 1, 0.3f, 0);

        oa1.setRepeatCount(ObjectAnimator.INFINITE);
        oa2.setRepeatCount(ObjectAnimator.INFINITE);
        oa3.setRepeatCount(ObjectAnimator.INFINITE);
        oa4.setRepeatCount(ObjectAnimator.INFINITE);

        getAnimatorAgent().playTogether(
                oa1, oa2, oa3, oa4
        );
    }
}
```

The result is a endless animation like the following (there's a glitch caused by the video<>gif converted)

![result](http://im.ezgif.com/tmp/ezgif-3549413059.gif)

Instead of using `ObjectAnimator.INFINITE`, you can pass in the number (integer) of times you want the animation to play. 

There are a few downsides to be worked on 
* Need to implement your own BaseViewAnimator. 
* `AnimatorListener.onRepeat()` callback is not currently being called.

**Comment by ghostofcain** [comment]
I agree that it would be a nice feature to have but there's another way to repeat the animation without changing the library. 

Just add a listener and when the animation ends, simply redo the animation. This can be done infinitely (by just doing it over and over again) or by having a counter and incrementing it on every onAnimationEnd() and checking that you haven't reached the "end" (i.e. your counter is less than the number of repeats). Whilst it's probably not the easiest solution, it works for me.

**Comment by robertoestivill** [comment]
@ghostofcain you don't have to modify the library. Just subclass `BaseViewAnimator` and pass it in to `YoYo.with( baseViewAnimator )`

**Comment by HarshavardhanHokage** [comment]
Right now I don't think repeat is supported but you can try the following work around. Create a method. Drop your animation within it and then add a listener to it. In onAnimationEnd call the method again.

Example:
```
 public void doYoyo(final Techniques techniques,final View view)
    {
        YoYo.with(techniques).duration(2000).interpolate(new LinearInterpolator()).withListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {

            }

            @Override
            public void onAnimationEnd(Animator animation) {
                doYoyo(techniques, view);
            }

            @Override
            public void onAnimationCancel(Animator animation) {

            }

            @Override
            public void onAnimationRepeat(Animator animation) {

            }
        }).playOn(view);
    }
```
```
doYoyo(Techniques.Landing, tv_title);
doYoyo(Techniques.RubberBand, tv_textView);
```
This way you can repeat the animations and also use a single method to try different animations on different views. You can even add other parameters like duration.

**Comment by zekedran** [comment]
A much easier solution, I believe

    Handler handler = new Handler();
    handler.post(new Runnable() {
                        @Override
                        public void run() {
                            YoYo.with(Techniques.Flash).duration(1500).playOn(tapToPlay);
                            handler.postDelayed(this,1500);
                        }
                    });

**Comment by zekedran** [comment]
I would still recommend having the feature .repeat(boolean) in YoYo function chain, which is greatly helpful.

**Comment by daimajia** [comment]
Thanks you all guys. 

I know I'm too late, but it comes finally. ❤️

**Comment by pcegarra** [comment]
Today repeat allow a number:

```
            YoYo.with(Techniques.Bounce)
                    .repeat(-1)
```
