### ISSUE TITLE
Animation leaves 'smudge' on screen

### ISSUE THREAD

**Issue by KevMHaube** [daimajia/AndroidViewAnimations#29]
When my animation starts, all is fine. It shows my view to me, and then begins the out animation. The out animation, however, leaves the last few frames of the transition as a 'smudge' on my view (as seen in the Circle View)
![screenshot_2014-11-23-01-31-46](https://cloud.githubusercontent.com/assets/8764261/5156806/9f458720-72b1-11e4-81d9-b6689ecfaf51.png)

**Comment by daimajia** [comment]
I think you are using double or more animation together, please check it. 

Close this issue, since no reply.
