### ISSUE TITLE
Interpolators have no effect

### ISSUE THREAD

**Issue by mrcodepanda** [daimajia/AndroidViewAnimations#30]
I tried a lot of interpolators and None of them have any effect on the animations. I'm doing it this way:

```
YoYo.with(Techniques.SlideOutDown)
    .duration(200)
    .interpolate(new BounceInterpolator())    // Nothing works here
    .withListener(new Animator.AnimatorListener() {
    @Override
    public void onAnimationStart(Animator animation) { }

        @Override
        public void onAnimationEnd(Animator animation) { }

        @Override
        public void onAnimationCancel(Animator animation) { }

        @Override
        public void onAnimationRepeat(Animator animation) { }
    })
    .playOn(view);
```

I think it might be related to `AnimationComposer` not calling `BaseViewAnimator`'s `setInterpolator()`.

**Comment by srujan7** [comment]
Even though, this issue seems to be resolved, interpolator is not making any difference in my case. Animation is happening same as it happened without interpolator.

    YoYo.with(Techniques.SlideInRight)
                    .duration(250)
                    .interpolate(new DecelerateInterpolator())
                    .playOn(searchTags);
