### ISSUE TITLE
Download jar from here

### ISSUE THREAD

**Issue by vyscond** [daimajia/AndroidViewAnimations#37]
Hey buddy, would you mind post .jar versions here on github? i really dont like to use mave. Thanks :)

**Comment by daimajia** [comment]
https://github.com/daimajia/AndroidViewAnimations#eclipse

**Comment by daimajia** [comment]
https://github.com/daimajia/AndroidViewAnimations/releases/download/v1.1.3/AndroidViewAnimations-1.1.3.jar
