### ISSUE TITLE
Has conflict with Gson

### ISSUE THREAD

**Issue by jjhesk** [daimajia/AndroidViewAnimations#39]
I have discovered there is a conflict with Gson compile. 

Warning:Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
Warning:Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
Warning:Dependency org.json:json:20090211 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
Warning:Dependency org.json:json:20090211 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages

**Comment by robertoestivill** [comment]
This library doesn't declare any dependency on Json nor Gson 
You can take a look at the library deployed pom:

https://repo1.maven.org/maven2/com/daimajia/androidanimations/library/1.1.3/library-1.1.3.pom

@jjhesk can you provide a little bit more context? Maybe you gradle dependencies? This sounds like it might be an issue coming from another included library. Thanks!

**Comment by lzyzsd** [comment]
@jjhesk may be you should provide more information, as @robertoestivill has pointed, this lib does not depend on org.json:json. I think your warning messages are caused by other libs that depend on org.json:json

**Comment by daimajia** [comment]
close since no reply.
