### ISSUE TITLE
How to reset or stop all animations

### ISSUE THREAD

**Issue by ControlAdad** [daimajia/AndroidViewAnimations#44]
How can one stop all animations on a view?

**Comment by stasbar** [comment]
I Have the same problem :+1:

**Comment by harshal2711** [comment]
I used SlideOutright animation on button and on animation end, screen is redirecting to other activity. I also want to reset animation. When new screen is finish() or user press back button is not visible because it slide out already and i want to reset it. How can i achieve that ?

**Comment by MarcusMa** [comment]
I used a duration with 0 to make the view reset:
`YoYo.with(Techniques.FadeIn).duration(0).playOn(xxxxx)`

**Comment by daimajia** [comment]
This feature has already been supported. You can control the animation with [YoYoString](https://github.com/daimajia/AndroidViewAnimations/blob/master/library/src/main/java/com/daimajia/androidanimations/library/YoYo.java#L223).
