### ISSUE TITLE
How to set the center point of animations?

### ISSUE THREAD

**Issue by TommyTC** [daimajia/AndroidViewAnimations#51]
Hi.
This is a very nice library to use animation in android.
But why it is different effect in my project ？such as DropOutAnimation.
I import it by gradle.
Can you help me to use if you have time ？
Thanks

**Comment by TommyTC** [comment]
I think the problem is not in the layout，Becuse I try use your layout.

**Comment by artemkutukov** [comment]
I have this problem to. I'm use CircleImageView in LinearLayout, animation start from left top. 
<LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/text"
            android:layout_centerHorizontal="true"
            android:gravity="bottom|center_horizontal"
            android:id="@+id/linearLayout18"
            android:layout_alignParentBottom="true">

            <de.hdodenhof.circleimageview.CircleImageView
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:id="@+id/photo1"
                android:layout_marginRight="10dp"
                android:layout_gravity="center"
                android:visibility="gone" />

            <de.hdodenhof.circleimageview.CircleImageView
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:id="@+id/photo2"
                android:layout_marginLeft="10dp"
                android:layout_gravity="center"
                android:visibility="gone" />
        </LinearLayout>

**Comment by artemkutukov** [comment]
I'm find problem! Problem with style android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"

**Comment by seshuvinay** [comment]
any update on how to fixthis? I have this problem too.

**Comment by andaluz** [comment]
Hello guys, **BounceIn** animation starts from **top-left** position of the view, but I want it from the **center** position of the view. How can I achieve that?

I like this library very much. I really appreciate the author of this project to share it with the community. If I only know how to fix this problem, I'd be very very happy.
Thank you.

**Comment by johntiror** [comment]
Hi, I found the same issue: **BounceIn **animation starts from **top-left** position of the view, but I want it from the center position of the view. How can I achieve that?
Thanks very much

**Comment by andaluz** [comment]
@johntiror I think this happens when you perform Bounce animation too soon. I haven't fixed it yet, but I think you need to perform the bounce animation when your view is finished rendering. There's a callback when for when the view is layed out, see this link: http://stackoverflow.com/a/7735122/1012775
I think that should fix your problem.

**Comment by johntiror** [comment]
Thanks, that's correct. it solved. Thanks!
