### ISSUE TITLE
Is not proguard friendly

### ISSUE THREAD

**Issue by kevintanhongann** [daimajia/AndroidViewAnimations#56]
Unable to identify which third party library in this library is affected by proguard.

**Comment by robertoestivill** [comment]
This sounds weird to me. I have absolutely no problem with this library and proguard. 
What error are you getting? Can you post your app dependencies and proguard configuration?

**Comment by kevintanhongann** [comment]
Think I need to close this. Because one of the other two dependencies of this library requires proguard entry. However, this should be documented.

**Comment by ppamorim** [comment]
@kevintanhongann Please show to me the code. I've the same issue.
