### ISSUE TITLE
Deprecate NineOlds

### ISSUE THREAD

**Issue by ppamorim** [daimajia/AndroidViewAnimations#57]
You can ViewCompat class instead this deprecated library.

**Comment by RubenGees** [comment]
+1

**Comment by mdesoto** [comment]
+1

**Comment by rizhilee** [comment]
+1

**Comment by frakc** [comment]
+1

**Comment by GuilhE** [comment]
+1

**Comment by bitsunami** [comment]
+1

**Comment by gkaffka** [comment]
+1

**Comment by shubhamchaudhary** [comment]
+1

**Comment by riadhnet** [comment]
+1

**Comment by daimajia** [comment]
Thanks all of you, the next version will be published in two days. It's totally removed `nineoldandroids`, since the Android 4.0 has become the major Android version.
Android also updated [`AnimationEasingFunctions`](https://github.com/daimajia/AnimationEasingFunctions) to 2.0.
