### ISSUE TITLE
Hide before animation

### ISSUE THREAD

**Issue by ChrisWoodard** [daimajia/AndroidViewAnimations#60]
This might be a stupid question but how do I hide the target view before the animation?  For example if I am using the Techniques.ZoomInUp animation I want the view to be hidden before the animation is applied; by default the image is displayed for a split second then hidden when the .playon() gets called (and then of course zooms back into view).

Thanks.

**Comment by RubenGees** [comment]
Well, you could just call view.setVisible(View.INVISBLE) on the View before playing the animation.

**Comment by ChrisWoodard** [comment]
Hi Ruben,

That's the route I took in the end, I just wanted to check I wasn't missing a trick.

Thanks for the quick response. :+1:
