### ISSUE TITLE
Progard profiles

### ISSUE THREAD

**Issue by rex3du** [daimajia/AndroidViewAnimations#68]
Hi 

When I use Progards, your library couldn't be referenced. 

I have already added -keep class com.daimajia.androidanimations.*\* { *; } into proguard-rules, but it doesn't work. Is there anyone know how to fix this?

**Comment by af6767** [comment]
-keep public class com.daimajia.** {*;} fix it for me

**Comment by DhimasAP88** [comment]
Hi 
i got same issue here, but when I implement using -keep public class com.daimajia.* {*;} is still give couldn't be referenced. Is there any suggestion to fix this?

**Comment by daimajia** [comment]
@DhimasAP88 Logs?

**Comment by coltwillcox** [comment]
Try with:
-keep class com.daimajia.easing.** { *; }
-keep interface com.daimajia.easing.** { *; }

**Comment by daimajia** [comment]
It's been fixed in new version. Try the latest version again.
