### ISSUE TITLE
Usage with support v7

### ISSUE THREAD

**Issue by Florent1510** [daimajia/AndroidViewAnimations#70]
Hi!

I'm trying to use the library with AppCompat and a TextView.

YoYo.with(Techniques.Landing)
                .duration(700)
                .interpolate(new AccelerateDecelerateInterpolator())
                .playOn(findViewById(R.id.welcome_text));

Makes it crash. I tried other activities, other views, it crashes every time with a "Can not init easingMethod instance"

How can I fix this?

Thanks!

**Comment by robertoestivill** [comment]
You are most likely missing one of the require dependencies ( com.daimija.easing )

From the readme

```
dependencies {
        compile 'com.nineoldandroids:library:2.4.0'
        compile 'com.daimajia.easing:library:1.0.1@aar'
        compile 'com.daimajia.androidanimations:library:1.1.3@aar'
}
```

**Comment by Florent1510** [comment]
Jup, and even weirder, I just compiled the Demo application using support v7 and it worked! So it has to be something with my layouts, most probably..


<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

    <include layout="@layout/view_toolbar"/>

    <HorizontalScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/button_layout"
        android:layout_below="@+id/toolbar"
        android:scrollbars="none"
        android:layout_centerInParent="true"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="horizontal"
            android:layout_centerVertical="true"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:gravity="center_vertical">

            <TextView
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:fontFamily="sans-serif-light"
                android:layout_marginRight="50dp"
                android:layout_marginLeft="25dp"
                android:textSize="28sp"
                android:text="@string/google_news_indicator"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                android:id="@+id/welcome_text"
                android:textAppearance="?android:attr/textAppearanceMedium"/>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                
                android:gravity="center"
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_top_stories"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_top_stories"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_world"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_world"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_business"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_business"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_technology"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_technology"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_entertainment"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_entertainment"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_sports"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_sports"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_science"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_science"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>

            <RelativeLayout
                android:background="#EEEEEE"
                android:layout_width="300dp"
                android:layout_height="300dp"
                android:layout_marginLeft="50dp"
                android:layout_marginRight="50dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:gravity="center"
                
                android:orientation="horizontal">

                <TextView
                    android:layout_height="match_parent"
                    android:layout_width="match_parent"
                    android:layout_marginLeft="20dp"
                    android:layout_marginRight="20dp"
                    android:layout_marginBottom="12.5dp"
                    android:textSize="30sp"
                    android:text="@string/google_news_health"
                    android:layout_centerHorizontal="true"
                    android:layout_centerVertical="true"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:textAppearance="?android:attr/textAppearanceMedium"/>

                <CheckBox
                    android:id="@+id/cb_health"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginBottom="25dp"/>

            </RelativeLayout>
        </LinearLayout>
    </HorizontalScrollView>

    <LinearLayout
        android:id="@+id/button_layout"
        style="?android:attr/buttonBarStyle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true">

        <Button
            style="?android:attr/buttonBarButtonStyle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="0.5"
            android:onClick="onClickCancel"
            android:id="@+id/button_cancel"
            android:text="@android:string/cancel"/>

        <Button
            style="?android:attr/buttonBarButtonStyle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="0.5"
            android:onClick="onClickOk"
            android:id="@+id/button_ok"
            android:text="@android:string/ok"/>
    </LinearLayout>

</RelativeLayout>

**Comment by Florent1510** [comment]
The issue was that I used ProGuard. If anyone knows how to make it work with ProGuard, I'd love to hear it. Thanks!

**Comment by Florent1510** [comment]
The issue was that I used ProGuard. If anyone knows how to make it work with ProGuard, I'd love to hear it. Thanks!

**Comment by rajukandasamy** [comment]
adding the following lines to my proguard-rules fixed the problem,

```
-keep class com.daimajia.easing.** { *; }
-keep interface com.daimajia.easing.** { *; }
```
