### ISSUE TITLE
drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.

### ISSUE THREAD

**Issue by bu2zhouzhu** [daimajia/AndroidViewAnimations#71]
D:\Code\AndroidViewAnimations-master\demo\build\intermediates\res\merged\debug\drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.
D:\Code\AndroidViewAnimations-master\demo\build\intermediates\res\merged\debug\drawable-hdpi\ic_launcher.png: Original is here. The version qualifier may be implied.
How should I solve this?

**Comment by bu2zhouzhu** [comment]
I solved the problem.
Open file library/build.gradle. Change
'com.daimajia.easing:library:1.0.0@aar' to
'com.daimajia.easing:library:1.0.1@aar'
See [here](https://github.com/daimajia/AndroidViewAnimations/issues/36)

**Comment by daimajia** [comment]
Sorry for the mistake I made.
