### ISSUE TITLE
Onrepeat function

### ISSUE THREAD

**Issue by fengnanyue** [daimajia/AndroidViewAnimations#72]
Do the animations have the onrepeat function? and btw, it would be better if there is a method to change the params of the animations directly.

**Comment by kashban** [comment]
Yes, there is such a function:

     YoYo.with(Techniques.FadeIn).duration(250)
                .withListener(new Animator.AnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animation) {
                        
                    }

                    @Override
                    public void onAnimationEnd(Animator animation) {}

                    @Override
                    public void onAnimationCancel(Animator animation) {}

                    @Override
                    public void onAnimationRepeat(Animator animation) {
                            // Looks like it, does it?
                    }
                })
                .playOn(lyt_ProgressBarOverlay);

**Comment by fengnanyue** [comment]
Awesome!
