### ISSUE TITLE
how to set pivot for animation

### ISSUE THREAD

**Issue by mreram** [daimajia/AndroidViewAnimations#74]
this is very useful library but there isn't any method to set pivot and set the center point of animation and it is very big problem. please try to create this method .
very tnX

**Comment by SakadiwaaSoftware** [comment]
I am also experiencing this problem. Particularly with 'RubberBand'. In some situations the animation starts from the centre of the view as expected, but in others it seems to bounce from the top-left of the view

**Comment by mreram** [comment]
@SakadiwaaSoftware  wava library support pivot 
https://github.com/hujiaweibujidao/wava
u can use this and enjoy! ;)
