### ISSUE TITLE
Rejected by "Google Play Store"

### ISSUE THREAD

**Issue by excitepv** [daimajia/AndroidViewAnimations#78]
Hi Daimajia, thanks for an awesome library. While adding the library in my project "Google Play Store" rejects my app with the following message **"We detected that at least one APK version in your recent upload isn’t using Android Pay correctly. Including APK version(s) 208 in your submission could cause your app to be rejected for violating our Payments policy"**. I know that **AndroidViewAnimations** is nothing to do with "Android Pay" up to my knowledge. Kindly help me to resolve the issue. Thanks in advance.

**Comment by reizamv** [comment]
what youre coding for google pay..please include in your post

**Comment by excitepv** [comment]
Hi reizamv , thanks for your reply. My app is not a paid app it is for specific educational institutions. Also I never used any  payment related features.

**Comment by excitepv** [comment]
If I remove those dependencies from grade the app is approved.
dependencies {
        compile 'com.nineoldandroids:library:2.4.0'
        compile 'com.daimajia.easing:library:1.0.1@aar'
        compile 'com.daimajia.androidanimations:library:1.1.3@aar'
}

**Comment by FridayShamblen** [comment]
Did this ever get resolved? Considering using this library....thanks.

**Comment by daimajia** [comment]
@FridayShamblen @excitepv @reizamv 

There is definitely **no** payment related source code in this library. It shall not be the problem of this lib.

Close this issue.
