### ISSUE TITLE
Crash App After Signed APK in Progaurd

### ISSUE THREAD

**Issue by daxeshzwt** [daimajia/AndroidViewAnimations#79]
my app is crash after generating signed apk but it is working in debug mode.
i think so that was the Progaurd Issue .

give it solution asap.

**Comment by mtkarimi** [comment]
I've done it like this :| i realized it when my app was in hand of customers and every things was crashing :))

-keep class com.daimajia.** { *; }
-keep interface com.daimajia.** { *; }
-keep public class com.daimajia.** {*;}

-keep class com.nineoldandroids.** { *; }
-keep interface com.nineoldandroids.** { *; }
-keep public class com.nineoldandroids.** {*;}

**Comment by daimajia** [comment]
check this https://github.com/daimajia/AndroidViewAnimations/issues/68

**Comment by HosseinKurd** [comment]
@mtkarimi it has some Errors

that's All i used :


`-keep class com.daimajia.*{ *; }`
`-keep interface com.daimajia.*{ *; }`
`-keep public class com.daimajia.*{ *; }`
`-keep class com.nineoldandroids.*{ *; }`
`-keep interface com.nineoldandroids.*{ *; }`
`-keep public class com.nineoldandroids.*{ *; }`
