### ISSUE TITLE
unnecessary dependency 

### ISSUE THREAD

**Issue by fmaxx** [daimajia/AndroidViewAnimations#82]
Hi, seems like you have "com.nineoldandroids:library" in your libs:

I got **java.util.zip.ZipException: duplicate entry: com/nineoldandroids/animation/Animator$AnimatorListener.class**

with: 

> compile 'com.nineoldandroids:library:2.4.0'
> compile 'com.daimajia.easing:library:1.0.1@aar'
> compile 'com.daimajia.androidanimations:library:1.1.3@aar'

But works ok:

> compile 'com.daimajia.easing:library:1.0.1@aar'
> compile 'com.daimajia.androidanimations:library:1.1.3@aar'

**Comment by daimajia** [comment]
Maybe you have already added `com.nineolddroids`, anyway the latests version has removed `nineoldandroids`.

Enjoy it.
