### ISSUE TITLE
set repeating on animations

### ISSUE THREAD

**Issue by tux-world** [daimajia/AndroidViewAnimations#83]
how can i set repeat() to loop animation until cancel repeating ?

**Comment by Eylen** [comment]
Do you mean to have it looping endlessly? I think that you've to pass -1 to repeat call.

**Comment by daimajia** [comment]
It's pretty obviously no one read the demo code. 

Check here: https://github.com/daimajia/AndroidViewAnimations/blob/master/demo/src/main/java/com/daimajia/androidanimations/MyActivity.java#L45

You can pass `YoYo.INFINITE` as the repeat parameter. Then it will repeat forever.

BTW. Thanks @Eylen for the answer.
