### ISSUE TITLE
java.lang.NoClassDefFoundError: com.daimajia.easing.Skill

### ISSUE THREAD

**Issue by srujan7** [daimajia/AndroidViewAnimations#84]
My app crashes with this error whenever I use this on my DescreetSeekbar view. 
error message:
`java.lang.NoClassDefFoundError: com.daimajia.easing.Skill`

**Comment by daimajia** [comment]
@srujan7 Please make sure that you have already import the `com.daimajia.easing:library:1.0.2@aar`

**Comment by srujan7** [comment]
@daimajia  I already have imported!

**Comment by srujan7** [comment]
@daimajia I already have imported!
