### ISSUE TITLE
How to use it for PopupWindow?

### ISSUE THREAD

**Issue by HanderWei** [daimajia/AndroidViewAnimations#85]
Hi, I would like use this library for PopupWindow. But this library just for Views.

How to change it for PopupWindow?

Any help will be highly appreciated.

**Comment by daimajia** [comment]
Check this method: https://developer.android.com/reference/android/widget/PopupWindow.html#getContentView() 

```java
YoYo.with(Techniques.Tada)
    .duration(700)
    .playOn(popup.getContentView());
```
