### ISSUE TITLE
NullPointerException when the animation end

### ISSUE THREAD

**Issue by csr91706** [daimajia/AndroidViewAnimations#91]
i have download your demo,and run it ,but when i touch one list item,it is broken.and show the NullPointerException .  i found if i set repeat 1,it is ok,but if i set others ,it is broken.
![q5ax3gc wryoddwl 70k ly](https://cloud.githubusercontent.com/assets/7697993/23243414/d475de0e-f9b9-11e6-9af6-654c7f869582.png)

**Comment by daimajia** [comment]
The demo apk, downloaded from the readme file?

BTW. Which Android version you are using?

**Comment by wzgl5533** [comment]
me too. But version is 5.0+, it's OK . Why ?

**Comment by wzgl5533** [comment]
我在5.0版本，没有问题，在4.2测试报错和楼上一样，请问作者这是什么原因？

**Comment by mandeep-vratesh** [comment]
I tried it on 4.4.4 and 4.1.1, it is giving the same exception.

**Comment by mandeep-vratesh** [comment]
It seems there is something with **.repeat()**. I observed that .repeat(5) was crashing on the second repetition/loop of the animation. So I removed it and tried and it did not crash. It is not working for .repeat(2) too.

**Comment by daimajia** [comment]
@wzgl5533 @mandeep-vratesh Which lib version you are trying?

**Comment by wzgl5533** [comment]
I try it according to your step,Do you test your code on  version 4+?

**Comment by mandeep-vratesh** [comment]
@daimajia I followed the readme. So it's 2.2

**Comment by daimajia** [comment]
@wzgl5533 @mandeep-vratesh Could any one show me the code context?

**Comment by mandeep-vratesh** [comment]
@daimajia [here](https://github.com/mandeep-vratesh/learning2) is my project that I am working on.

**Comment by Lakedaemon** [comment]
Got the same problem with this : 
YoYo.with(Techniques.Shake)
                            .duration(700)
                            .repeat(-1)
                            .delay(3000)
                            .playOn(download)

where download is a Button

I got a NPE that crashs my app after 2 shakes (at the end of the second shake ?)
java.lang.NullPointerException
    at  android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd (AnimatorSet.java : 797)
    at  android.animation.ValueAnimator.endAnimation (ValueAnimator.java : 1056)
    at  android.animation.ValueAnimator.access$400 (ValueAnimator.java : 50)
    at  android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java : 644)
    at  android.animation.ValueAnimator$AnimationHandler.run (ValueAnimator.java : 660)
    at  android.view.Choreographer$CallbackRecord.r un (Choreographer.java : 813)
    at  android.view.Choreographer.doCallbacks (Choreographer.java : 613)
    at  android.view.Choreographer.doFrame (Choreographer.java : 582)
    at  android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java : 799)
    at  android.os.Handler.handleCallback (Handler.java : 733)
    at  android.os.Handler.dispatchMessage (Handler.java : 95)
    at  android.os.Looper.loop (Lo oper.java : 146)
    at  android.app.ActivityThread.main (ActivityThread.java : 5679)
    at  java.lang.reflect.Method.invokeNativeNative Method
    at  java.lang.reflect.Method.invoke (Method.java : 515)
    at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java : 1291)
    at  com.android.internal.os.ZygoteInit.main (ZygoteInit.java : 1107)
    at  dalvik.system.NativeStart.mainNative Method

**Comment by Lakedaemon** [comment]
Could this be related to this issue (observed in another library) ? 
https://github.com/KeepSafe/TapTargetView/issues/121

Basically : on some devices, touching the view hierarchy in on Animation End make it throw an Exception 
because of a buggy ViewGroup implementation ?

**Comment by abdulrahmanmajeed** [comment]
I guess you are passing a null object. and may be the problem with repeat() function because after first time when you came again the object is null ...

**Comment by CValeron** [comment]
Anyone found a solution to this ?

**Comment by Lakedaemon** [comment]
The screen doesn't change when the issue appears : 
I can reproduce it 100% : I inflate the view, I start the infinite animation on a view that is layed out and not null, I don't touch the view (I just wait for the issue to happen) and... the app crashes

I grepped some code and I think that the issue and the stack trace leads to the folowing version of AnimatorSet (android 4.4.4 r_1) : 

Node animNode = mAnimatorSet.mNodeMap.get(animation) at line 796 returns null and then line 797 throws

792         @SuppressWarnings("unchecked")
793         public void More ...onAnimationEnd(Animator animation) {
794             animation.removeListener(this);
795             mPlayingSet.remove(animation);
796             Node animNode = mAnimatorSet.mNodeMap.get(animation);
797             animNode.done = true;
798             if (!mTerminated) {
799                 // Listeners are already notified of the AnimatorSet ending in cancel() or
800                 // end(); the logic below only kicks in when animations end normally
801                 ArrayList<Node> sortedNodes = mAnimatorSet.mSortedNodes;
802                 boolean allDone = true;
803                 int numSortedNodes = sortedNodes.size();
804                 for (int i = 0; i < numSortedNodes; ++i) {
805                     if (!sortedNodes.get(i).done) {
806                         allDone = false;
807                         break;
808                     }
809                 }
810                 if (allDone) {
811                     // If this was the last child animation to end, then notify listeners that this
812                     // AnimatorSet has ended
813                     if (mListeners != null) {
814                         ArrayList<AnimatorListener> tmpListeners =
815                                 (ArrayList<AnimatorListener>) mListeners.clone();
816                         int numListeners = tmpListeners.size();
817                         for (int i = 0; i < numListeners; ++i) {
818                             tmpListeners.get(i).onAnimationEnd(mAnimatorSet);
819                         }
820                     }
821                     mAnimatorSet.mStarted = false;
822                     mAnimatorSet.mPaused = false;
823                 }
824             }
825         }

As Said before, the only animation code I'm using is 

YoYo.with(Techniques.Shake)
.duration(700)
.repeat(-1)
.delay(3000)
.playOn(download)

on a  Button whose name is download and which is inflated, layed out and not null

**Comment by Lakedaemon** [comment]
investigating further : mNodeMap is mostly used in builders... and in the clone() method that is used to repeat the animation.

And it looks like they changed the implementation of clone() between 4.4.4_r1 and 5.1.0_r1
http://grepcode.com/file_/repository.grepcode.com/java/ext/com.google.android/android/5.1.0_r1/android/animation/AnimatorSet.java/?v=diff&id2=4.4.4_r1

So there might be something wrong with the clone() method... for 4.4.4

**Comment by Lakedaemon** [comment]
A workaround for this issue is to handle the repeat process yourself, 
for example with RxJava : 

`Observable.interval(2000, 3700, TimeUnit.MILLISECONDS).observeOn(AndroidSchedulers.mainThread()).subscribe {
            YoYo.with(Techniques.Shake)
                    //.delay(3000)
                    .duration(700)
                    // .repeat(-1)
                    .playOn(button)
        }`

I guess that a way fixto fix that  would be to change the way Yoyo handles repetitions : 
instead of using the clone() method in onanimationEnd() which looks unreliable, 
store or implement a clone() method for the builder in the yoyo library and, at each repetition, create an animation from scratch from the builder

l

**Comment by daimajia** [comment]
@Lakedaemon Thanks for your information. I'll do some research on this issue, It's actually pretty annoying that the [AnimatorSet](https://developer.android.com/reference/android/animation/AnimatorSet.html) has been set to final class descriptor... I have no idea why the made that.

**Comment by Tinker-S** [comment]
It seems that we could not use AnimatorSet.clone() method. I have an idea, we can setRepeatCount for each ValueAnimator which in AnimatorSet. Then play together will work as we expected.

**Comment by SirWellington** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7860281-288439948_4-s1-v1.png?transparent=1&palette=1&width=246)
Any updates on this?

**Comment by gsc1234567890woshishui** [comment]
一样还是崩溃！为啥不修复好可惜的一个项目没法用了

**Comment by mjal146** [comment]
I have this problem too in android 4.4

**Comment by daimajia** [comment]
Hi guys, sorry for my late reply, there was something terrible happened to my family two month ago, so I disappeared for a while. Anyway, This issue has been fixed, new version will be published in maven ASAP. 

Thanks @Tinker-S .

**Comment by conghongjie** [comment]
could you tell me how to fix ?
