### ISSUE TITLE
SlideOutRight alpha to 0

### ISSUE THREAD

**Issue by csr91706** [daimajia/AndroidViewAnimations#92]
if i not change your code ,how can i set alpha to 1.

**Comment by daimajia** [comment]
Create a new Animator which extends from BaseViewAnimator and then remove [Line 39](https://github.com/daimajia/AndroidViewAnimations/blob/master/library/src/main/java/com/daimajia/androidanimations/library/sliders/SlideOutRightAnimator.java#L39)
