### ISSUE TITLE
Animate menu items/toolbars

### ISSUE THREAD

**Issue by Gilwe** [daimajia/AndroidViewAnimations#93]
Hi,
Im using AppCompactActivity with toolbar using the theme XML (not "Toolbar" view),
my app has a simple selectable list which the user can trigger selection mode on and off.
whenever the mode changes I change the visabillity of a trash icon on the toolbar, but it look kinda bad so I would like to use the YoYo class to has a nice fade for the tooldbar/delete icon but it doesn't seem to work.

Is there a way for me to manage this?
Thank you!

**Comment by daimajia** [comment]
You need get the view of the toolbar icon layout view first. Then invoke the YoYo methods.
