### ISSUE TITLE
如果让View的动效穿过它的父控件,进入到其他控件中?

### ISSUE THREAD

**Issue by sweet2o09** [daimajia/AndroidViewAnimations#94]
```java
new SlideOutDownAnimator() {
            @Override
            public void prepare(View target) {
                ViewGroup parent = (ViewGroup) target.getParent();
                int distance = parent.getHeight() - target.getTop();
                getAnimatorAgent().playTogether(
                        ObjectAnimator.ofFloat(target, "alpha", 1, 0),
                        ObjectAnimator.ofFloat(target, "translationY", 0, distance)
                );
            }
        }
```
parent.getHeight(),我把这个改成其他控件的参数,结果得出的distance 是正确的,但是动画效果,在parent 边界就消失了

**Comment by daimajia** [comment]
It's basically not possible to do what you say ( Change it's parent node after animation finished ). 

But you can do some trick when you layout the Views. Like the following figure:

for example, Red box, and green box are ViewGroup, the Yellow circle is the view you want to change it's parent node.

 if you want to make the yellow circle move to the green box bottom when the animation finished, you actually need to make the red box wrap the green box, and then move the yellow circle inside the red box. 

![image](https://cloud.githubusercontent.com/assets/2503423/23684691/62978608-03db-11e7-84d6-0f8a7d7cd99b.png)
