### ISSUE TITLE
Fade in rather than intended animation when view first displayed

### ISSUE THREAD

**Issue by HolySamosa** [daimajia/AndroidViewAnimations#95]
I'm trying to use `SlideInLeft` when the visibility is set for a particular view.  for some inexplicable reason, the first time this code executes, the view fades in rather than slides in,  I thought perhaps if could be an issue with `android:animateLayoutChanges="true"`, however I have explicitly set it to false.

Any ideas?  I've tried various hacks to achieve the desired behavior, but nothing has thus far worked.
```java
    public void setNewLabelVisible(boolean isVisible) {
        this.layoutNewLabel.setVisibility(isVisible ? VISIBLE : INVISIBLE);
        if (isVisible) {
            YoYo.with(Techniques.SlideInLeft)
                    .duration(1000)
                    .playOn(layoutNewLabel);
        }
    }
```

**Comment by daimajia** [comment]
Hi, when you are execute the animation, please make sure that the view has enough room to slide in. Just like this figure: 

![image](https://cloud.githubusercontent.com/assets/2503423/23781696/027f64f6-058a-11e7-8485-904816cd7ad5.png)

**Comment by daimajia** [comment]
Close this issue, if you are still confused, it will be opened again.

**Comment by srujan7** [comment]
The same is happening with me. I have applied slideInUp animation which happens to a fragment on button click. The first time I click on the button after app restart, no animation happen, there after, It happens as expected.

**Comment by sandysultan** [comment]
anyone solved this?

**Comment by LuiguiBalarezo** [comment]
Aun persiste el problema con el FadeInUp y slideInUp.
Solo funciona con el código de ejemplo dentro del mismo proyecto, pero no funciona usandolo en un proyecto propio con AndroidX.

Alguna solución? 
Gracias.

**Comment by LuiguiBalarezo** [comment]
/********** App Gradle ***********/

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.zetagas.myapplication"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.android.support:support-compat:25.1.1'
    implementation 'com.daimajia.easing:library:2.0@aar'
    implementation 'com.daimajia.androidanimations:library:2.3@aar'
}

/**************** Layout Activity Main .xml **************/

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/textexample"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:text="hOLA"
        android:textSize="40sp" />

</RelativeLayout>

/******************** MainLayout.java ********************/
package com.zetagas.myapplication;

import android.animation.Animator;
import android.os.Bundle;
import android.view.animation.AccelerateDecelerateInterpolator;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.daimajia.androidanimations.library.Techniques;
import com.daimajia.androidanimations.library.YoYo;

public class MainActivity extends AppCompatActivity {

    private TextView text;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        text = findViewById(R.id.textexample);
        YoYo.with(Techniques.FadeInUp)
                .duration(1200)
                .repeat(YoYo.INFINITE)
                .interpolate(new AccelerateDecelerateInterpolator())
                .withListener(new Animator.AnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animation) {

                    }

                    @Override
                    public void onAnimationEnd(Animator animation) {
                    }

                    @Override
                    public void onAnimationCancel(Animator animation) {

                    }

                    @Override
                    public void onAnimationRepeat(Animator animation) {

                    }
                })
                .playOn(text);
    }
}

/******* IMAGE *****/
![image](https://user-images.githubusercontent.com/5883067/71835155-dc676e80-307e-11ea-8348-cba94bdbe9d8.png)
