### ISSUE TITLE
how to Create facebook LIKE button animation

### ISSUE THREAD

**Issue by amane** [daimajia/AndroidViewAnimations#96]
Hey,
I have a card layout where each card has like button just like facebook. I want to animate the like button just like facebook does or would love to know any other method better than facebook?

**Comment by daimajia** [comment]
Are you seeking this sort of animation? Check this link: https://github.com/ChadCSong/ShineButton

![](https://github.com/ChadCSong/ShineButton/raw/master/demo_shine_others.gif)
