### ISSUE TITLE
Animation Not Working while phone is in Battery Saver Mode

### ISSUE THREAD

**Issue by katepratik** [daimajia/AndroidViewAnimations#98]
I have being using the lib for a while but recently I came across this issue while my Moto G4 Plus android version Nougat was on Battery Saver mode all my animations vanished away.
Please look into the issue and get it solved in your next lib update. Also, if you could come up with a quick fix for now that would be great for me.

**Comment by daimajia** [comment]
It's disabled by the system when the system in Battery Save mode, so I can do nothing on that.
