### ISSUE TITLE
How to make sequence  animation?

### ISSUE THREAD

**Issue by iman2420** [daimajia/AndroidViewAnimations#99]
Hi. i want to make sequence  in animations.
How to do it?

**Comment by kashban** [comment]
https://github.com/daimajia/AndroidViewAnimations/issues/67

**Comment by iman2420** [comment]
This means using this code to display 4 animations???

     `YoYo.with(Techniques.FadeIn).duration(250)
                        .withListener(new Animator.AnimatorListener() {
                            @Override
                            public void onAnimationStart(Animator animation) {
                                AppLog.Log(TAG, "onAnimationStart");
                            }

                            @Override
                            public void onAnimationEnd(Animator animation) {
                                AppLog.Log(TAG, "onAnimationEnd");
                                YoYo.with(Techniques.FadeIn).duration(250)
                                        .withListener(new Animator.AnimatorListener() {
                                            @Override
                                            public void onAnimationStart(Animator animation) {

                                            }

                                            @Override
                                            public void onAnimationEnd(Animator animation) {
                                                YoYo.with(Techniques.FadeIn).duration(250)
                                                        .withListener(new Animator.AnimatorListener() {
                                                            @Override
                                                            public void onAnimationStart(Animator animation) {
                                                            }

                                                            @Override
                                                            public void onAnimationEnd(Animator animation) {
                                                                YoYo.with(Techniques.FadeIn).duration(250)
                                                                        .withListener(new Animator.AnimatorListener() {
                                                                            @Override
                                                                            public void onAnimationStart(Animator animation) {
                                                                            }

                                                                            @Override
                                                                            public void onAnimationEnd(Animator animation) {
                                                                                YoYo.with(Techniques.FadeIn).duration(250)
                                                                                        .withListener(new Animator.AnimatorListener() {
                                                                                            @Override
                                                                                            public void onAnimationStart(Animator animation) {
                                                                                            }

                                                                                            @Override
                                                                                            public void onAnimationEnd(Animator animation) {
                                                                                                // Start new animation here
                                                                                            }

                                                                                            @Override
                                                                                            public void onAnimationCancel(Animator animation) {
                                                                                            }

                                                                                            @Override
                                                                                            public void onAnimationRepeat(Animator animation) {
                                                                                                // This is being called when the animation starts over, I guess
                                                                                            }
                                                                                        })
                                                                                        .playOn(tableRow5);
                                                                            }

                                                                            @Override
                                                                            public void onAnimationCancel(Animator animation) {
                                                                            }

                                                                            @Override
                                                                            public void onAnimationRepeat(Animator animation) {
                                                                                // This is being called when the animation starts over, I guess
                                                                            }
                                                                        })
                                                                        .playOn(tableRow4);
                                                            }

                                                            @Override
                                                            public void onAnimationCancel(Animator animation) {
                                                            }

                                                            @Override
                                                            public void onAnimationRepeat(Animator animation) {
                                                                // This is being called when the animation starts over, I guess
                                                            }
                                                        })
                                                        .playOn(tableRow3);
                                            }

                                            @Override
                                            public void onAnimationCancel(Animator animation) {
                                            }

                                            @Override
                                            public void onAnimationRepeat(Animator animation) {
                                                // This is being called when the animation starts over, I guess
                                            }
                                        })
                                        .playOn(tableRow2);
                            }

                            @Override
                            public void onAnimationCancel(Animator animation) {
                                AppLog.Log(TAG, "onAnimationCancel");

                            }

                            @Override
                            public void onAnimationRepeat(Animator animation) {
                                AppLog.Log(TAG, "onAnimationRepeat");
                            }
                        })
                        .playOn(tableRow1);`

**Comment by Sofrosyn** [comment]
Chain each preceding animation to the onEnd listener of the previous view 

>  YOYO.with(Technique.tada).(duration).onEnd(anime1 ->{
          YoYo.with(Technique.tada).(duration).onEnd(anime2->{
        //Add more animation

}).playOn(viewTwo)
}).playOn(viewOne)

**Comment by iman2420** [comment]
i finally found a solution:

     `private int index = 0;
     viewArray = new View[]{lyt_parts, lytWages, lytVat, lytTransportation, lytCompanyShareAmount, lytCustomerShareAmount};
    animateLayouts(viewArray[index]);
    private void animateLayouts(View view) {


        YoYo.with(Techniques.StandUp).withListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {
                view.setVisibility(View.VISIBLE);
            }

            @Override
            public void onAnimationEnd(Animator animation) {
                index++;
                if (index < viewArray.length)
                    animateLayouts(viewArray[index]);
            }

            @Override
            public void onAnimationCancel(Animator animation) {

            }

            @Override
            public void onAnimationRepeat(Animator animation) {

            }
        }).playOn(view);
    }`
